/* -------------------------------------------------------------------------- */

# docker-compose up     => Compose multiple containers to work together

/* -------------------------------------------------------------------------- */

version: '3'
services:
    frontend:
        build: ./frontend
        ports:
            - '3000:3000'

    api:
        build: ./backend
        ports:
            - '5050:5050'
